# Generated by Django 4.2.7 on 2025-09-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='categorias/', verbose_name='Imagen representativa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('tipo_producto', models.CharField(choices=[('medicamento', 'Medicamento'), ('alimento', 'Alimento'), ('servicio', 'Servicio'), ('accesorio', 'Accesorio'), ('equipo', 'Equipo médico')], max_length=20, verbose_name='Tipo de producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('principio_activo', models.CharField(blank=True, max_length=200, verbose_name='Principio activo')),
                ('concentracion', models.CharField(blank=True, max_length=100, verbose_name='Concentración')),
                ('laboratorio', models.CharField(blank=True, max_length=100, verbose_name='Laboratorio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
