# Generated by Django 4.2.7 on 2025-09-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (CLP $)'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de la cita')),
                ('tipo_cita', models.CharField(choices=[('consulta_general', 'Consulta General'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('control', 'Control'), ('emergencia', 'Emergencia'), ('estetica', 'Estética'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de cita')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=15, verbose_name='Estado')),
                ('motivo', models.TextField(verbose_name='Motivo de la consulta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('veterinario', models.CharField(blank=True, max_length=200, verbose_name='Veterinario asignado')),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio estimado (CLP $)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
