# Generated by Django 4.2.7 on 2025-09-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_alter_producto_precio_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Tipo de animal')),
                ('descripcion', models.TextField(verbose_name='Descripción del tipo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tipos_animales/', verbose_name='Imagen del tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Animal',
                'verbose_name_plural': 'Tipos de Animales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('numero_colegiado', models.CharField(blank=True, max_length=50, verbose_name='Número de colegiado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('medicamento', 'Medicamento'), ('alimento', 'Alimento para mascotas'), ('servicio', 'Servicio veterinario'), ('accesorio', 'Accesorio para mascotas'), ('equipo', 'Equipo médico veterinario')], max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (años)')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('tamaño', models.CharField(blank=True, choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], max_length=15, verbose_name='Tamaño')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color/Coloración')),
                ('propietario_nombre', models.CharField(max_length=200, verbose_name='Nombre del propietario')),
                ('propietario_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del propietario')),
                ('propietario_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del propietario')),
                ('propietario_direccion', models.TextField(blank=True, verbose_name='Dirección del propietario')),
                ('numero_chip', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de microchip')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones médicas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto de la mascota')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.tipoanimal', verbose_name='Tipo de animal')),
                ('veterinario_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinaria.veterinario', verbose_name='Veterinario encargado')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombre'],
            },
        ),
    ]
